// Auto-generated by gen_linker.py
// Memory map parameters

localparam ADR_IMEM_START = 32'h00002000;
localparam ADR_PMEM_START = 32'h00004800;
localparam ADR_DMEM_START = 32'h00005000;

localparam ADR_IMEM_SIZE  = 8192;
localparam ADR_PMEM_SIZE  = 2048;
localparam ADR_DMEM_SIZE  = 16384;
